name: ganpati_desktop
description: GANPATI BAPPA MORYA

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  auto_animated: ^3.2.0
  marquee_widget: ^1.2.0
  toast: ^0.3.0
  flutter_html: ^3.0.0-beta.2
  modal_bottom_sheet: ^3.0.0
  avatar_glow: ^3.0.1
  url_launcher: ^6.2.6
  animated_background: ^2.0.0
  expandable: ^5.0.1
  flip_card: ^0.7.0
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.2
  http: ^1.2.1
  rflutter_alert: ^2.0.7
  contained_tab_bar_view: ^0.8.0
  bitsdojo_window: ^0.1.6
  tuple: ^2.0.2
  dart_vlc: ^0.4.0
  file_saver: ^0.2.12
  desktoasts: ^0.0.3
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
  assets:
    - assets/images/

msix_config:
  display_name: GANPATI BAPPA
  publisher_display_name: MANISH MAHESH TALREJA
  identity_name: 7213MANISHMAHESHTALREJA.MY-BSCITQUIZ
  msix_version: 4.0.0.0
  certificate_path: C:\Users\MMT\Desktop\GANESH.pfx
  certificate_password: 9833137409
  publisher: CN=40FB6399-30D2-4930-A104-C7F44AC71E90
  logo_path: C:\Users\MMT\Desktop\MSIX ICON.png
  start_menu_icon_path: C:\Users\MMT\Desktop\MSIX ICON.png
  tile_icon_path: C:\Users\MMT\Desktop\MSIX ICON.png
  vs_generated_images_folder_path: C:\Users\MMT\Desktop\Assets\
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'
  store: true